from __future__ import annotations
import hashlib, json, re, shutil, tempfile, threading, time
from pathlib import Path
from typing import Any
from .config import COMM_CFG, COMM_CSS, COMM_PLUGIN_DIR, COMM_WEBFONTS, COMM_WEBROOT, DOC_DEST, MANAGED_DIR, STATE_DIR, sh
from .fonts import download_emoji, download_family, load_state, local_manifests, save_state

APPLY_LOCK = threading.Lock()

def docker_ps() -> list[tuple[str, str]]:
    cp = sh(["docker", "ps", "--format", "{{.Names}}|{{.Image}}"]); out=[]
    for line in cp.stdout.splitlines():
        if "|" in line: out.append(tuple(line.split("|",1)))
    return out

def find_container(role: str) -> str | None:
    for name,image in docker_ps():
        line=f"{name} {image}".lower()
        if role=="community" and ("communityserver" in line or "community-server" in line): return name
        if role=="document" and ("documentserver" in line or "document-server" in line): return name
    return None

def docker_exec(container: str, *args: str, check: bool=True):
    return sh(["docker","exec",container,*args],check=check)

def build_mail_css(manifests: list[dict[str,Any]]) -> str:
    lines=["/* Generated by ONLYOFFICE Font Manager. Do not edit. */"]
    for m in manifests:
        if m.get("type")=="emoji": continue
        family=str(m["family"]).replace("\\","\\\\").replace('"','\\"')
        for item in m.get("files",[]):
            rel=item["file"].replace("\\","/"); ext=Path(rel).suffix.lower()
            fmt={".ttf":"truetype",".otf":"opentype",".woff":"woff",".woff2":"woff2"}.get(ext,"truetype")
            lines += ["@font-face {",f'  font-family: "{family}";',f'  src: url("fonts/{rel}") format("{fmt}");',f"  font-weight: {item.get('weight','400')};",f"  font-style: {item.get('style','normal')};","  font-display: swap;","}"]
    return "\n".join(lines)+"\n"

EMOJI_PLUGIN = r'''(function(){
var E=[['Smileys','😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉 😌 😍 🥰 😘 😋 😜 🤪 🤓 😎 🥳 😏 😒 😔 😢 😭 😤 😡 🤬 🤯 😱 😴 🤢 🤮 🤧 😷 🤒 🤕'],['People','👍 👎 👌 🤌 ✌️ 🤞 🤟 🤘 🤙 👈 👉 👆 👇 ☝️ ✋ 🤚 🖐️ 🖖 👋 🤝 👏 🙌 👐 🤲 🙏 ✍️ 💪 🦾 🧠 👀 👁️ 👂 🦻 👃'],['Hearts','❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 ❣️ 💕 💞 💓 💗 💖 💘 💝 💟'],['Animals','🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐨 🐯 🦁 🐮 🐷 🐸 🐵 🐔 🐧 🐦 🦆 🦉 🐴 🦄 🐝 🦋 🐌 🐞 🐢 🐍 🦎 🦖 🐙 🐠 🐬 🐳'],['Food','🍏 🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🫐 🍒 🍑 🥭 🍍 🥝 🍅 🥑 🍆 🥔 🥕 🌽 🌶️ 🫑 🥒 🥬 🥦 🍞 🥐 🥨 🧀 🍳 🍕 🍔 🍟 🌭 🍿 🍰 ☕ 🍺 🍷'],['Things','⌚ 📱 💻 ⌨️ 🖥️ 🖨️ 🖱️ 💾 💿 📀 📷 📺 📻 🎙️ 🎧 🎵 🎶 📚 📎 ✂️ 🔒 🔑 🔨 🪛 🔧 ⚙️ 💡 🔥 🎉 🎁 ✅ ❌ ⚠️ ℹ️ ♿'],['Travel','🚗 🚕 🚌 🚑 🚒 🚚 🚲 🛵 🏍️ 🚂 ✈️ 🚀 🚁 ⛵ 🚤 🚢 🏠 🏡 🏢 🏰 🗼 🗽 🌍 🌎 🌏 ☀️ 🌤️ 🌧️ ❄️ ⚡ 🌈']];
CKEDITOR.plugins.add('ooemoji',{init:function(editor){editor.ui.addRichCombo('OOEmoji',{label:'😀',title:'Emoji',toolbar:'insert,50',panel:{css:[CKEDITOR.skin.getPath('editor')].concat(editor.config.contentsCss||[]),multiSelect:false},init:function(){for(var i=0;i<E.length;i++){this.startGroup(E[i][0]);var a=E[i][1].split(' ');for(var j=0;j<a.length;j++){if(a[j])this.add(a[j],a[j],a[j]);}}},onClick:function(v){editor.focus();editor.fire('saveSnapshot');editor.insertText(v);editor.fire('saveSnapshot');}});}});
})();
'''

def patch_ckeditor_config(text: str, families: list[str], cache_key: str) -> str:
    start="    /* ONLYOFFICE_FONT_MANAGER_BEGIN */"; end="    /* ONLYOFFICE_FONT_MANAGER_END */"
    if start in text and end in text:
        before,rest=text.split(start,1); _,after=rest.split(end,1); text=before.rstrip()+"\n"+after.lstrip("\n")
    anchor='    config.font_names = fonts.join(";");'
    if anchor not in text: raise RuntimeError("Could not find CKEditor font_names anchor")
    entries=[f"{f}/{f}" for f in sorted(dict.fromkeys(families),key=str.casefold)]
    block=f'''\n    /* ONLYOFFICE_FONT_MANAGER_BEGIN */
    var ooFontManagerFonts = {json.dumps(entries,ensure_ascii=False)};
    var ooFontManagerNames = config.font_names.split(";");
    ooFontManagerFonts.forEach(function(font) {{ if (ooFontManagerNames.indexOf(font) === -1) ooFontManagerNames.push(font); }});
    ooFontManagerNames.sort();
    config.font_names = ooFontManagerNames.join(";");
    var ooFontManagerCss = "/UserControls/Common/ckeditor/onlyoffice-font-manager/fonts.css?v={cache_key}";
    if (!config.contentsCss) config.contentsCss = [];
    else if (typeof config.contentsCss === "string") config.contentsCss = [config.contentsCss];
    config.contentsCss = config.contentsCss.filter(function(css) {{ return css.indexOf("/onlyoffice-font-manager/fonts.css") === -1; }});
    config.contentsCss.push(ooFontManagerCss);
    var ooExtra = (config.extraPlugins || "").split(",").filter(Boolean);
    if (ooExtra.indexOf("ooemoji") === -1) ooExtra.push("ooemoji");
    config.extraPlugins = ooExtra.join(",");
    /* ONLYOFFICE_FONT_MANAGER_END */\n'''
    return text.replace(anchor,anchor+block,1)

def copy_managed_tree(src: Path, dest: Path):
    if dest.exists(): shutil.rmtree(dest)
    shutil.copytree(src,dest)

def sync_community(manifests: list[dict[str,Any]], work: Path) -> dict[str,Any]:
    comm=find_container("community")
    if not comm: raise RuntimeError("ONLYOFFICE Community Server container not found")
    if docker_exec(comm,"test","-f",COMM_CFG,check=False).returncode!=0: raise RuntimeError(f"CKEditor config not found in {comm}: {COMM_CFG}")
    css=build_mail_css(manifests); css_path=work/"fonts.css"; css_path.write_text(css); cache_key=hashlib.sha256(css.encode()).hexdigest()[:16]
    current=work/"config.js"; sh(["docker","cp",f"{comm}:{COMM_CFG}",str(current)]); original=current.read_text()
    backup=STATE_DIR/"backups"/("config.js."+hashlib.sha256(original.encode()).hexdigest()+".original"); backup.parent.mkdir(parents=True,exist_ok=True)
    if "ONLYOFFICE_FONT_MANAGER_BEGIN" not in original and not backup.exists(): backup.write_text(original)
    families=[m["family"] for m in manifests if m.get("type")!="emoji"]; current.write_text(patch_ckeditor_config(original,families,cache_key))
    docker_exec(comm,"rm","-rf",COMM_WEBROOT); docker_exec(comm,"mkdir","-p",COMM_WEBFONTS,COMM_PLUGIN_DIR)
    sh(["docker","cp",str(MANAGED_DIR)+"/.",f"{comm}:{COMM_WEBFONTS}/"]); sh(["docker","cp",str(css_path),f"{comm}:{COMM_CSS}"])
    plugin=work/"plugin.js"; plugin.write_text(EMOJI_PLUGIN); sh(["docker","cp",str(plugin),f"{comm}:{COMM_PLUGIN_DIR}/plugin.js"]); sh(["docker","cp",str(current),f"{comm}:{COMM_CFG}"])
    docker_exec(comm,"chown","-R","onlyoffice:onlyoffice",COMM_WEBROOT,COMM_PLUGIN_DIR,COMM_CFG,check=False); docker_exec(comm,"chmod","-R","a+rX",COMM_WEBROOT,COMM_PLUGIN_DIR,check=False); docker_exec(comm,"chmod","0644",COMM_CFG,COMM_CSS,f"{COMM_PLUGIN_DIR}/plugin.js",check=False)
    docker_exec(comm,"grep","-q","ONLYOFFICE_FONT_MANAGER_BEGIN",COMM_CFG); sh(["docker","restart","--timeout","30",comm])
    return {"container":comm,"families":len(families),"restarted":True}

def sync_document(manifests: list[dict[str,Any]]) -> dict[str,Any]:
    doc=find_container("document")
    if not doc: raise RuntimeError("ONLYOFFICE Document Server container not found")
    docker_exec(doc,"rm","-rf",DOC_DEST); docker_exec(doc,"mkdir","-p",DOC_DEST); sh(["docker","cp",str(MANAGED_DIR)+"/.",f"{doc}:{DOC_DEST}/"]); docker_exec(doc,"fc-cache","-f",check=False)
    generated=False
    if docker_exec(doc,"test","-x","/usr/bin/documentserver-generate-allfonts.sh",check=False).returncode==0:
        docker_exec(doc,"/usr/bin/documentserver-generate-allfonts.sh"); generated=True
    return {"container":doc,"families":len(manifests),"generated":generated}

def apply_selection(font_ids: list[str], emoji: bool, full_packs: bool) -> dict[str,Any]:
    with APPLY_LOCK:
        for fid in font_ids:
            if not re.fullmatch(r"[a-z0-9-]+",fid): raise ValueError(f"Invalid font id: {fid}")
        with tempfile.TemporaryDirectory(prefix="oofm-apply-") as td:
            root=Path(td); staged=root/"managed"; staged.mkdir(); manifests=[]; local_by_id={m["id"]:m for m in local_manifests()}
            for fid in sorted(set(font_ids)):
                if fid.startswith("local-"):
                    if fid not in local_by_id: raise RuntimeError(f"Local font not found: {fid}")
                    m=local_by_id[fid]; dest=staged/fid; dest.mkdir(parents=True,exist_ok=True); srcdir=Path(m["files"][0].get("source","")).parent if m.get("files") else None
                    for f in m["files"]:
                        src=Path(f.get("source") or (srcdir/Path(f["file"]).name)); shutil.copy2(src,dest/src.name)
                    manifests.append(m)
                else: manifests.append(download_family(fid,staged,full_packs))
            if emoji: manifests.append(download_emoji(staged))
            (staged/"manifest.json").write_text(json.dumps(manifests,indent=2,ensure_ascii=False))
            old=root/"previous-managed"; old_manifests=[]
            if MANAGED_DIR.exists() and any(MANAGED_DIR.iterdir()):
                shutil.copytree(MANAGED_DIR,old); mf=old/"manifest.json"
                if mf.exists():
                    try: old_manifests=json.loads(mf.read_text())
                    except Exception: old_manifests=[]
            copy_managed_tree(staged,MANAGED_DIR); work=root/"work"; work.mkdir()
            try:
                community=sync_community(manifests,work); document=sync_document(manifests)
            except Exception:
                if old.exists():
                    copy_managed_tree(old,MANAGED_DIR)
                    if old_manifests:
                        rw=root/"rollback"; rw.mkdir(exist_ok=True)
                        try: sync_community(old_manifests,rw)
                        except Exception as e: print("Community rollback failed:",e)
                        try: sync_document(old_manifests)
                        except Exception as e: print("Document rollback failed:",e)
                raise
            state={"fonts":sorted(set(font_ids)),"emoji":bool(emoji),"fullPacks":bool(full_packs),"appliedAt":int(time.time())}; save_state(state)
            return {"ok":True,"state":state,"community":community,"document":document,"manifest":manifests}

def status_data() -> dict[str,Any]:
    try: comm=find_container("community"); doc=find_container("document")
    except Exception: comm=doc=None
    return {"state":load_state(),"community":comm,"document":doc,"local":local_manifests(),"managedExists":(MANAGED_DIR/"manifest.json").exists()}
