from __future__ import annotations
import html, json
from .config import APP_VERSION, BASE_PATH, MAX_UPLOAD, csrf_value

def login_html(error: str="") -> str:
    err=f'<p style="color:#b42318">{html.escape(error)}</p>' if error else ""
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Font Manager Login</title><style>body{{font:15px system-ui;background:#f5f6f8;display:grid;place-items:center;min-height:100vh;margin:0}}form{{background:#fff;border:1px solid #ddd;border-radius:12px;padding:24px;width:min(380px,90vw)}}input,button{{width:100%;padding:10px;box-sizing:border-box;margin-top:10px}}button{{background:#ff6f3d;color:#fff;border:0;border-radius:6px}}</style></head><body><form method="post" action="{BASE_PATH}/login"><h2>ONLYOFFICE Font Manager</h2><p>Administrator sign-in</p>{err}<input type="password" name="password" autofocus placeholder="Admin password"><button>Sign in</button></form></body></html>'''

def app_html() -> str:
    csrf=csrf_value()
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ONLYOFFICE Font Manager</title>
<style>
:root{{--bg:#f5f6f8;--card:#fff;--text:#24262b;--muted:#69707d;--line:#dfe3e8;--accent:#ff6f3d;--good:#238636}}*{{box-sizing:border-box}}body{{margin:0;font:14px system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}}header{{height:58px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 22px;gap:12px;position:sticky;top:0;z-index:5}}header h1{{font-size:18px;margin:0}}header .badge{{background:#222;color:#fff;border-radius:12px;padding:3px 8px;font-size:11px}}main{{max-width:1280px;margin:auto;padding:18px}}.toolbar,.panel{{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px;margin-bottom:14px}}.toolbar{{display:grid;grid-template-columns:minmax(240px,1fr) 180px auto auto;gap:10px;align-items:center}}input,select,button{{font:inherit}}input[type=text],input[type=password],select{{width:100%;padding:9px 10px;border:1px solid #cfd5dc;border-radius:7px;background:#fff}}button{{padding:9px 14px;border-radius:7px;border:1px solid #cfd5dc;background:#fff;cursor:pointer}}button.primary{{background:var(--accent);border-color:var(--accent);color:white;font-weight:650}}button:disabled{{opacity:.5;cursor:not-allowed}}.tabs{{display:flex;gap:6px;margin-bottom:12px}}.tabs button.active{{background:#222;color:#fff}}.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(245px,1fr));gap:10px}}.font-card{{background:#fff;border:1px solid var(--line);border-radius:9px;padding:12px;min-height:112px;display:flex;flex-direction:column;gap:7px}}.font-card.selected{{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}}.font-top{{display:flex;align-items:center;gap:8px}}.font-name{{font-weight:700}}.meta{{font-size:12px;color:var(--muted)}}.preview{{font-size:24px;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}.row{{display:flex;gap:10px;align-items:center;flex-wrap:wrap}}.grow{{flex:1}}.muted{{color:var(--muted)}}#toast{{position:fixed;right:18px;bottom:18px;max-width:520px;padding:12px 14px;background:#222;color:#fff;border-radius:8px;display:none;white-space:pre-wrap;z-index:9}}.source-card{{background:#fff;border:1px solid var(--line);border-radius:9px;padding:14px}}.source-card a{{color:#0969da;text-decoration:none}}.source-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:10px}}.hidden{{display:none}}@media(max-width:800px){{.toolbar{{grid-template-columns:1fr}}}}
</style></head><body><header><h1>ONLYOFFICE Font Manager</h1><span class="badge">Mail + Docs</span><span class="grow"></span><span id="engineStatus" class="muted">Checking engines…</span></header><main>
<div class="panel row"><strong id="selectedCount">0 selected</strong><label><input id="emoji" type="checkbox" checked> Colour emoji pack</label><label><input id="fullPacks" type="checkbox" checked> Complete language packs</label><span class="grow"></span><button id="apply" class="primary">Apply to Mail + Docs</button></div>
<div class="tabs"><button data-tab="library" class="active">Open font library</button><button data-tab="installed">Installed / selected</button><button data-tab="sources">More open sources</button></div>
<section id="library"><div class="toolbar"><input id="search" type="text" placeholder="Search 2,000+ open fonts…"><select id="category"><option value="">All categories</option><option>sans-serif</option><option>serif</option><option>display</option><option>handwriting</option><option>monospace</option></select><label><input id="variable" type="checkbox"> Variable only</label><button id="clear">Clear filters</button></div><div id="fontGrid" class="grid"></div><div class="row" style="justify-content:center;margin:16px"><button id="more">Load more</button></div></section>
<section id="installed" class="hidden"><div class="panel"><h3 style="margin-top:0">Current managed set</h3><div id="installedText" class="muted">Nothing applied yet.</div></div><div id="installedGrid" class="grid"></div></section>
<section id="sources" class="hidden"><div class="panel"><strong>Other open-font catalogues</strong><p class="muted">Fontsource is fully automatic. Where another site does not provide a safe redistributable API, download the font there and import it below. The manager then pushes it to both ONLYOFFICE engines.</p></div><div class="source-grid">
<div class="source-card"><b>Open Foundry</b><p>Curated open-source typefaces.</p><a target="_blank" rel="noopener" href="https://open-foundry.com/">Open catalogue ↗</a></div><div class="source-card"><b>FontSpace — Open</b><p>Open-font discovery; this manager does not mirror FontSpace files.</p><a target="_blank" rel="noopener" href="https://www.fontspace.com/category/open">Open catalogue ↗</a></div><div class="source-card"><b>Fontshare</b><p>Check each family licence before importing.</p><a target="_blank" rel="noopener" href="https://www.fontshare.com/">Open catalogue ↗</a></div><div class="source-card"><b>The League of Moveable Type</b><p>Open-source type foundry.</p><a target="_blank" rel="noopener" href="https://www.theleagueofmoveabletype.com/">Open catalogue ↗</a></div><div class="source-card"><b>Velvetyne Type Foundry</b><p>Libre and open-source fonts.</p><a target="_blank" rel="noopener" href="https://velvetyne.fr/">Open catalogue ↗</a></div></div>
<div class="panel" style="margin-top:14px"><h3 style="margin-top:0">Import a downloaded open font</h3><div class="row"><input id="uploadFile" type="file" accept=".ttf,.otf,.woff,.woff2"><input id="licenseNote" class="grow" type="text" placeholder="Licence / source note (e.g. SIL OFL 1.1)"><button id="uploadBtn">Import</button></div><p class="muted">TTF, OTF, WOFF or WOFF2. The file stays local to your ONLYOFFICE host.</p></div></section></main><div id="toast"></div>
<script>
const BASE={json.dumps(BASE_PATH)},CSRF={json.dumps(csrf)},MAX_UPLOAD={MAX_UPLOAD};let fonts=[],selected=new Set(),localFonts=[],renderLimit=120,state={{emoji:true,fullPacks:true}};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(msg,good=false){{let t=$('#toast');t.textContent=msg;t.style.background=good?'#1f6f3d':'#222';t.style.display='block';setTimeout(()=>t.style.display='none',7000)}}async function api(path,opt={{}}){{opt.headers=Object.assign({{'X-CSRF-Token':CSRF}},opt.headers||{{}});let r=await fetch(BASE+path,opt),ct=r.headers.get('content-type')||'',d=ct.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error((d&&d.error)||d||('HTTP '+r.status));return d}}function escapeHtml(s){{return String(s??'').replace(/[&<>"]/g,m=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}}[m]))}}
function updateCount(){{$('#selectedCount').textContent=selected.size+' font'+(selected.size===1?'':'s')+' selected';$('#emoji').checked=!!state.emoji;$('#fullPacks').checked=state.fullPacks!==false}}function addPreview(card,f){{if(card.dataset.preview||f.type==='local')return;card.dataset.preview='1';let family='OOFM_'+f.id.replace(/-/g,'_'),st=document.createElement('style');st.textContent=`@font-face{{font-family:"${{family}}";src:url("${{BASE}}/api/preview/${{encodeURIComponent(f.id)}}.woff2") format("woff2");font-display:swap}}`;document.head.appendChild(st);card.querySelector('.preview').style.fontFamily='"'+family+'",sans-serif'}}const observer=new IntersectionObserver(es=>es.forEach(e=>{{if(e.isIntersecting)addPreview(e.target,e.target._font)}}),{{rootMargin:'250px'}});
function fontCard(f){{let c=document.createElement('div');c.className='font-card'+(selected.has(f.id)?' selected':'');c._font=f;c.innerHTML=`<div class="font-top"><input type="checkbox" ${{selected.has(f.id)?'checked':''}}><div><div class="font-name">${{escapeHtml(f.family)}}</div><div class="meta">${{escapeHtml(f.category||'other')}} · ${{escapeHtml(f.type||'open')}}</div></div></div><div class="preview">The quick brown fox 123</div><div class="meta">${{(f.weights||[]).length||1}} weights · ${{(f.styles||[]).join(', ')||'normal'}}</div>`;let box=c.querySelector('input');box.onchange=()=>{{box.checked?selected.add(f.id):selected.delete(f.id);c.classList.toggle('selected',box.checked);updateCount()}};observer.observe(c);return c}}
function filtered(){{let q=$('#search').value.trim().toLowerCase(),cat=$('#category').value,v=$('#variable').checked;return fonts.filter(f=>(!q||(f.family||'').toLowerCase().includes(q)||f.id.includes(q))&&(!cat||f.category===cat)&&(!v||f.variable))}}function renderFonts(reset=false){{if(reset)renderLimit=120;let a=filtered(),g=$('#fontGrid');g.innerHTML='';a.slice(0,renderLimit).forEach(f=>g.appendChild(fontCard(f)));$('#more').style.display=a.length>renderLimit?'inline-block':'none'}}function renderInstalled(){{let map=new Map([...fonts,...localFonts].map(f=>[f.id,f])),g=$('#installedGrid');g.innerHTML='';[...selected].map(id=>map.get(id)||{{id,family:id}}).forEach(f=>g.appendChild(fontCard(f)));$('#installedText').textContent=state.appliedAt?'Last applied: '+new Date(state.appliedAt*1000).toLocaleString():'Selection not yet applied.'}}
async function init(){{try{{let [cat,st]=await Promise.all([api('/api/catalog'),api('/api/status')]);fonts=cat;state=st.state||state;selected=new Set(state.fonts||[]);localFonts=st.local||[];$('#engineStatus').textContent='Mail: '+(st.community||'not found')+' · Docs: '+(st.document||'not found');updateCount();renderFonts(true);renderInstalled()}}catch(e){{toast(e.message)}}}}
$('#search').oninput=()=>renderFonts(true);$('#category').onchange=()=>renderFonts(true);$('#variable').onchange=()=>renderFonts(true);$('#clear').onclick=()=>{{$('#search').value='';$('#category').value='';$('#variable').checked=false;renderFonts(true)}};$('#more').onclick=()=>{{renderLimit+=120;renderFonts()}};$('#emoji').onchange=e=>state.emoji=e.target.checked;$('#fullPacks').onchange=e=>state.fullPacks=e.target.checked;
$('#apply').onclick=async()=>{{let b=$('#apply');b.disabled=true;b.textContent='Applying…';try{{let r=await api('/api/apply',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{fonts:[...selected],emoji:state.emoji,fullPacks:state.fullPacks}})}});state=r.state;renderInstalled();toast('Applied successfully to Mail and Document Server.\\nCommunity: '+r.community.container+'\\nDocs: '+r.document.container,true)}}catch(e){{toast('Apply failed: '+e.message)}}finally{{b.disabled=false;b.textContent='Apply to Mail + Docs'}}}};
$$('.tabs button').forEach(b=>b.onclick=()=>{{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');['library','installed','sources'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==b.dataset.tab));if(b.dataset.tab==='installed')renderInstalled()}});
$('#uploadBtn').onclick=async()=>{{let f=$('#uploadFile').files[0];if(!f)return toast('Choose a font file first.');if(f.size>MAX_UPLOAD)return toast('File is too large.');let bytes=new Uint8Array(await f.arrayBuffer()),bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));try{{let r=await api('/api/upload',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{name:f.name,data:btoa(bin),license:$('#licenseNote').value}})}});localFonts.push(r.font);selected.add(r.font.id);updateCount();renderInstalled();toast('Imported '+r.font.family+'. It is selected and ready to apply.',true)}}catch(e){{toast(e.message)}}}};init();
</script></body></html>'''
